export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const SET_PSEUDO = 'SET_PSEUDO';
export type SET_PSEUDO = typeof SET_PSEUDO;

export const GET_PSEUDO = 'GET_PSEUDO';
export type GET_PSEUDO = typeof GET_PSEUDO;